package router

import (
	"github.com/01121531/subandnew-api/controller"
	"github.com/01121531/subandnew-api/middleware"
	"github.com/01121531/subandnew-api/service/authz"
	"github.com/gin-gonic/gin"
)

func registerMailboxRoutes(engine *gin.Engine, api *gin.RouterGroup) {
	admin := api.Group("/mailbox-management")
	admin.Use(controller.MailboxAuditTrail(), middleware.AdminAuth(), controller.MailboxAdminOriginGuard)
	view := controller.MailboxGuard(authz.MailboxView)
	manage := controller.MailboxGuard(authz.MailboxManage)
	assign := controller.MailboxGuard(authz.MailboxAssign)
	operators := controller.MailboxGuard(authz.MailboxOperators)
	review := controller.MailboxGuard(authz.MailboxReview)
	admin.GET("/accounts", view, controller.ListMailboxAccounts)
	admin.POST("/accounts/query", view, controller.ListMailboxAccounts)
	admin.POST("/accounts/change-status", view, review, controller.ChangeMailboxAccountStatus)
	admin.POST("/accounts/export-completed", view, review, controller.MailboxGuard(authz.MailboxCredentials), controller.ExportCompletedMailboxAccounts)
	admin.POST("/accounts/export-all", view, review, controller.MailboxGuard(authz.MailboxCredentials), controller.ExportMailboxData(false))
	admin.POST("/issues/export", view, review, controller.MailboxGuard(authz.MailboxCredentials), controller.ExportMailboxData(true))
	admin.POST("/accounts/archive", manage, controller.ArchiveMailboxAccounts(false))
	admin.POST("/accounts/restore", manage, controller.ArchiveMailboxAccounts(true))
	admin.GET("/accounts/:id", view, controller.GetMailboxAccount)
	admin.GET("/account-operators", view, controller.MailboxAccountOperators)
	admin.POST("/accounts/:id/credentials", controller.MailboxGuard(authz.MailboxCredentials), controller.GetMailboxCredentials)
	admin.POST("/accounts/:id/temporary-cvv", manage, controller.MailboxGuard(authz.MailboxCredentials), controller.ProvideMailboxTemporaryCVV)
	admin.POST("/accounts/:id/clear-cvv", manage, controller.MailboxGuard(authz.MailboxCredentials), controller.ClearMailboxCVV)
	admin.POST("/imports/preview", manage, controller.ImportMailboxAccounts(true))
	admin.POST("/imports", manage, controller.ImportMailboxAccounts(false))
	admin.POST("/assignments", assign, controller.AssignMailboxAccounts)
	admin.GET("/assignment-repairs", view, assign, review, controller.ListMailboxAssignmentRepairs)
	admin.POST("/assignment-repairs", view, assign, review, controller.RepairMailboxAssignments)
	admin.GET("/operator-options", assign, controller.MailboxOperatorOptions)
	admin.GET("/operators", operators, controller.ListMailboxOperators)
	admin.GET("/operators/:id/work-summary", operators, view, review, controller.GetMailboxOperatorWorkSummary)
	admin.GET("/operators/:id/work-accounts", operators, view, review, controller.ListMailboxOperatorWorkAccounts)
	admin.GET("/operators/:id/work-accounts/:account_id/history", operators, view, review, controller.GetMailboxOperatorAccountHistory)
	admin.POST("/operators", operators, controller.SaveMailboxOperator)
	admin.PUT("/operators/:id", operators, controller.SaveMailboxOperator)
	admin.POST("/operators/:id/password", operators, controller.ResetMailboxOperatorPassword)
	admin.POST("/operators/:id/revoke-sessions", operators, controller.RevokeMailboxOperatorSessions)
	admin.GET("/submissions", review, controller.ListMailboxSubmissions)
	admin.PATCH("/submissions/:id/remark", view, review, controller.EditMailboxRemark)
	admin.GET("/submissions/:id/remark-history", view, review, controller.GetMailboxRemarkHistory)
	admin.GET("/issues", review, controller.ListMailboxIssues)
	admin.POST("/issues/query", view, review, controller.ListMailboxIssues)
	admin.GET("/issue-operators", review, controller.MailboxAccountOperators)
	admin.GET("/issues/:id", review, controller.GetMailboxIssue)
	admin.POST("/issues/:id/resolve", review, controller.ResolveMailboxIssue)
	admin.GET("/import-options", manage, controller.GetMailboxImportOptions)
	admin.POST("/submissions/:id/review", review, controller.ReviewMailboxSubmission)
	admin.GET("/attachments/:id", controller.MailboxAttachmentGuard, controller.ReadMailboxAttachment)
	admin.GET("/audits", controller.MailboxGuard(authz.MailboxAudit), controller.ListMailboxAudits)

	portal := engine.Group("/mailbox-api/v1")
	portal.Use(middleware.RouteTag("api"), middleware.GlobalAPIRateLimit(), controller.MailboxAuditTrail())
	portal.POST("/auth/login", middleware.AnonymousRequestBodyLimit(), controller.LoginMailboxPortal)
	portal.GET("/auth/session", controller.GetMailboxPortalSession)
	portal.Use(controller.MailboxPortalGuard)
	portal.POST("/auth/logout", controller.LogoutMailboxPortal)
	portal.POST("/auth/password", controller.ChangeMailboxPortalPassword)
	portal.GET("/accounts", controller.ListMailboxAccounts)
	portal.GET("/accounts/:id", controller.GetMailboxAccount)
	portal.POST("/accounts/:id/credentials", controller.GetMailboxCredentials)
	portal.GET("/submissions", controller.ListMailboxSubmissions)
	portal.PATCH("/submissions/:id/remark", controller.EditMailboxRemark)
	portal.GET("/submissions/:id/remark-history", controller.GetMailboxRemarkHistory)
	portal.GET("/issues", controller.ListMailboxIssues)
	portal.GET("/issues/:id", controller.GetMailboxIssue)
	portal.POST("/assignments/:id/issues", controller.SubmitMailboxIssue)
	portal.POST("/assignments/:id/attachments", controller.UploadMailboxAttachment)
	portal.POST("/assignments/:id/submit", controller.SubmitMailboxScreenshots)
	portal.GET("/attachments/:id", controller.ReadMailboxAttachment)
}
